config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#welcome'

  get '/signup', to: 'readers#new'
  post '/signup', to: 'readers#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#destroy'

  # Omniauth log in route with Google 
  get '/auth/:provider/callback', to: 'sessions#google'

  # nested routes

  # '/lists/:id/books'
  resources :lists do
    resources :books
  end 
  resources :books

  # '/readers/:id/lists'
  # using shallow routing nesting only what is necessary
  # in this case, reader_id is important
  # because list is expected to be created by a particular reader
  # new action is not used as a reader should not create list for other readers
  resources :readers do
    resources :lists, only: [:index]
  end 

  resources :genres, only: [:index, :show]

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :lists, dependent: :destroy
    # has_many :list_genres
    # has_many :lists, through: :list_genres
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

    def index 
        @genres = Genre.all.includes(:lists)
    end 

    def show
        @genre = Genre.find_by_id(params[:id])
    end 

    def new
        @genre = Genre.new
    end 

end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/index.html.erb
<ul>
    <% @genres.each do |genre| %>
        <li>
            <%= link_to genre.name, genre_path(genre) %>
                <ol>
                    <% genre.lists.each do |list| %>
                        <li><%= link_to list.title, list_path(list) %></li>
                    <% end %>
                </ol>
        </li>
    <% end %>
</ul>

app/views/genres/show.html.erb
<h1>
    <%= @genre.name %> - <%= pluralize(@genre.lists.count, "lists") %>
</h1>

<ol>
    <% @genre.lists.each do |list| %>
        <li><%= link_to list.title, list_path(list) %></li>
    <% end %>
</ol>