config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#welcome'

  get '/signup', to: 'readers#new'
  post '/signup', to: 'readers#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#destroy'

  # Omniauth log in route with Google 
  get '/auth/:provider/callback', to: 'sessions#google'

  # nested routes

  # '/lists/:id/books'
  resources :lists do
    resources :books
  end 
  resources :books

  # '/readers/:id/lists'
  # using shallow routing nesting only what is necessary
  # in this case, reader_id is important
  # because list is expected to be created by a particular reader
  # new action is not used as a reader should not create list for other readers
  resources :readers do
    resources :lists, only: [:index]
  end 

  resources :genres, only: [:index, :show]

end

app/models/list.rb
class List < ApplicationRecord
    belongs_to :reader
    belongs_to :genre
    has_many :books, dependent: :destroy
    has_many :readers, through: :books, dependent: :destroy
    # has_many :list_genres
    # has_many :genres, through: :list_genres

    validates :title, :description, presence: true
    validates :description, length: { maximum: 10, too_long: "%{count} characters is the maximum allowed" }
    # custom validator max reading lists a reader can create a day
    validate :daily_create_list_limit
    # accepts_nested_attributes_for :books

    # enables class method genre.name is accessible to list object
    delegate :name, to: :genre

    # scope method enables lists listed in alpha order
    # it only works when active record relation is true and it can be chained to objects
    scope :list_by_order, -> { order(:title) }

    # nested attributes method accepts nested values via params
    def genre_attributes=(genre)
        self.genre = Genre.find_or_create_by(name: genre[:name]) if !genre[:name].blank?
    end 

    def daily_create_list_limit
        today_lists = reader.lists.select do |list|
            reader.created_at.to_date == Date.today
        end 
        if today_lists.size > 3
            errors.add(:reader_id, "can't created more than 3 reading lists per user a day")
        end
    end 

    def self.search(params)
        List.where("lists.title LIKE :term OR lists.description LIKE :term", term: "%#{params}%")
    end 
    
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :set_list_by_id, only: [:edit, :update]

    def new 
        # if params[:reader_id] && @reader = Reader.find_by(params[:reader_id])
        #     @list = @reader.posts.build
        # else 
            @list = List.new
        # end 
            @list.build_genre
    end 

    def create
        @list = current_reader.lists.build(list_params)
        if @list.save
            redirect_to lists_path
        else
            render :new
        end 
    end 

    def index 
        if params[:reader_id]
            if @reader = Reader.find_by(id: params[:reader_id])
                @lists = @reader.lists.list_by_order
            end 
        else 
            @error = "Reader does not exist" if params[:reader_id]
            @lists = List.list_by_order
        end 

        if params[:search] && !params[:search].empty?
            @lists = @lists.search(params[:search]).list_by_order
        end 
    end 

    def show
        @list = List.find_by_id(params[:id])
        redirect_to lists_path if !@list
    end 
    
    def edit
        
        if !@list || @list.reader != current_reader
            redirect_to lists_path
        end 
        @list.build_genre if !@list.genre
    end 

    def update
      
        if !@list || @list.reader != current_reader
            redirect_to lists_path
        end 
        if @list.update(list_params)
            redirect_to list_path(@list)
        else 
            render :edit
        end 
    end 

    def destroy
        @list = List.find(params[:id])
        @list.destroy
        redirect_to lists_path
    end 

    private

    def list_params
        params.require(:list).permit(:title, :description, :genre_id, genre_attributes: [:name])
    end 

    def set_list_by_id
        @list = List.find_by(id: params[:id])
    end 
  
end

app/helpers/lists_helper.rb
module ListsHelper

    def a_reader_or_all_readers_reading_list
        if @reader
          content_tag(:h1, "#{@reader.username}'s reading list:")
        else
          content_tag(:h1, "All reading lists")
        end
      end

end

app/views/lists/edit.html.erb
<h1>Edit reading list <%= @list.title %></h1>

<%= render partial: "layouts/errors", locals: { object: @list } %>

<%= form_for(@list) do |f| %>

    <%= f.label :title %><br>
    <%= f.text_field :title %><br>

    <%= f.label :description %><br>
    <%= f.text_area :description %><br>

    <%= f.submit %>

<% end %>

app/views/lists/index.html.erb
<%= a_reader_or_all_readers_reading_list %>

    <%= form_tag(lists_path, method: :get) do %>
        <%= label_tag(:search, "Search List: ") %>
        <%= text_field_tag(:search) %>
        <%= submit_tag("Search") %>
    <% end %>

<ul>
    <% @lists.each do |list| %>
    <li>List Name: <%= link_to list.title, list_path(list) %> Description: <%= list.description %></li>
    <% end %>
</ul>

app/views/lists/new.html.erb
<h1>Create a new reading list</h1>

<%= render partial: "layouts/errors", locals: { object: @list } %>

<%= form_for(@list) do |f| %>

    <%= f.label "select a genre for the list" %>
    <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: true %><br>

    <p>Or create a new genre: 
        <%= f.fields_for :genre do |g| %>
        <%= g.text_field :name %>
        <% end %>
    </p>
    <br>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br>

    <%= f.label :description %><br>
    <%= f.text_area :description %><br>

    <%= f.submit %>

<% end %>

app/views/lists/show.html.erb
<h2>List Title: <%= @list.title %></h2>
   
<h2>List Description: <%= @list.description %></h2>

<% if @list.reader == current_reader %>
    <%= link_to "Edit this list", edit_list_path(@list) %>

    <p>Delete this list
        <%= button_to "Delete", list_path(@list), method: :delete, data: { confirm: "Are you sure to delete this list?"}%>
    </p>

<% end %>

<% if !@list.books.empty? %>
    <p><%= link_to "View all books", list_books_path(@list) %></p>
<% end %>

<h2>Books in this list</h2>
    <% @list.books.each do |book| %>
        <p>
            <strong>Book title: </strong>
            <%= book.title %>
        </p>
        <p>
            <strong>Book author: </strong>
            <%= book.author %>
        </p>
        <p>
            <strong>Note: </strong>
            <%= book.note %>
        </p>
    <% end %>

<% if @list.reader == current_reader %>
<h2>Add a book to this list</h2>
    <%= form_for @list.books.build do |form| %>
        <%= form.hidden_field :list_id %>

        <p>
            <%= form.label :title %>
            <%= form.text_field :title%>
        </p>
        <p>
            <%= form.label :author %>
            <%= form.text_field :author %>
        </p>
        <p>
            <%= form.label :note %>
            <%= form.text_field :note %>
        </p>
        <p>
            <%= form.submit "Create a book" %>
        </p>
    <% end %>
<% end %>