config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#welcome'

  get '/signup', to: 'readers#new'
  post '/signup', to: 'readers#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#destroy'

  # Omniauth log in route with Google 
  get '/auth/:provider/callback', to: 'sessions#google'

  # nested routes

  # '/lists/:id/books'
  resources :lists do
    resources :books
  end 
  resources :books

  # '/readers/:id/lists'
  # using shallow routing nesting only what is necessary
  # in this case, reader_id is important
  # because list is expected to be created by a particular reader
  # new action is not used as a reader should not create list for other readers
  resources :readers do
    resources :lists, only: [:index]
  end 

  resources :genres, only: [:index, :show]

end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :reader
    belongs_to :list
    
    validates :title, presence: true
    validates :title, uniqueness: true
    validates :author, presence: true

    scope :order_books_by_title, -> { order(:title) }
    # scope :group_books_by_author, -> { group(:author) }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :set_book, only: [:show, :edit, :update, :destroy]
    
    def index 
        if params[:list_id] && @list = List.find_by(id: params[:list_id])
        # if params[:list_id]
            # @books = List.find(params[:list_id]).books
            @books = @list.books.order_books_by_title
        else
            @error = "This list does not exist" if params[:list_id]
            @books = Book.all.order_books_by_title
        end 
    end 

    def new 
        if params[:list_id] && @list = List.find_by(id: params[:list_id])
            @book = @list.books.build
        else
            @error = "This list does not exist" if params[:list_id]
            @book = Book.new
        end 
    end 

    def create
        # @list = List.find(params(:list_id))
        # @book = @list.books.create(book_params)
        # redirect_to list_path(@list)
        @book = current_reader.books.build(book_params)
        if @book.save
            redirect_to book_path(@book)
        else 
            render :new
        end 
    end 

    def show 
    end 

    def edit
    end 

    def update
        if @book.update(book_params)
            redirect_to book_path(@book)
        else 
            render :edit
        end 
    end 

    def destroy
        @book.destroy
        redirect_to books_path
    end 

    private

    def book_params
        params.require(:book).permit(:list_id, :title, :author, :note)
    end 

    def set_book
        @book = Book.find_by(id: params[:id])
    end


end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Edit this book: <%= @book.title %>

<%= render partial: "layouts/errors", locals: { object: @book } %>

<%= form_for([@book]) do |f|%>
    <p>
        <%= f.label :list %>
        <%= f.collection_select :list_id, List.all, :id, :title %>
    </p>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %><br>
    </p> 
    <br>
    <p>
        <%= f.label :author %><br>
        <%= f.text_area :author %><br>
    </p>
    <br>
    <p>
        <%= f.label :note %><br>
        <%= f.text_area :note %><br>
    </p>
    <br>
    <%= f.submit %>

<% end %>

app/views/books/index.html.erb
<% if @list %>
    <h1>Books for <%= @list.title %></h1>
<% else %>
    <h1>All books</h1>
<% end %>

<ul>
    <% @books.each do |book| %>
        <li>Book title: <%= link_to book.title, book_path(book) %> | Author: <%= book.author %> | Note by reader: <%= book.note %> | Created by <%= book.reader.username %>.</li>
    <% end %>
</ul>

app/views/books/new.html.erb
<% if @book.list %>
    <h1>Add a new book to the reading list of <%= @book.list.title %></h1>
<% else %>
    <h1>Add a new book to a list<h1>
<% end %>

<%= render partial: "layouts/errors", locals: { object: @book } %>

<%= form_for([@book.list, @book]) do |f|%>

    <% if !@book.list %>
        <%= f.label :list%>
        <%= f.collection_select :list_id, List.all, :id, :title %>
    <% else %>
        <%= f.hidden_field :list_id %>
    <% end %>

    <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %><br>
    </p>
    <br>
    <p>
        <%= f.label :author %><br>
        <%= f.text_area :author %><br>
    </p>
    <br>
    <p>
        <%= f.label :note %><br>
        <%= f.text_area :note %><br>
    </p>
    <br>
    <%= f.submit %>

<% end %>

app/views/books/show.html.erb
<h2>Book title: <%= @book.title %></h2><br>
<h2>Book author: <%= @book.author %></h2><br>
<h2>Book note: <%= @book.note %></h2><br>

<% if @book.reader == current_reader %>
    
    <%= link_to "Edit this book", edit_book_path(@book) %>
    <p>Delete this book
        <%= button_to "Delete", list_book_path(@book.list, @book), method: :delete %>
    </p>
    
<% end %>

<h3>Back to the reading list this book belongs: <%= link_to @book.list.title, list_path(@book.list_id) %><h3>