config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#welcome'

  get '/signup', to: 'readers#new'
  post '/signup', to: 'readers#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#destroy'

  # Omniauth log in route with Google 
  get '/auth/:provider/callback', to: 'sessions#google'

  # nested routes

  # '/lists/:id/books'
  resources :lists do
    resources :books
  end 
  resources :books

  # '/readers/:id/lists'
  # using shallow routing nesting only what is necessary
  # in this case, reader_id is important
  # because list is expected to be created by a particular reader
  # new action is not used as a reader should not create list for other readers
  resources :readers do
    resources :lists, only: [:index]
  end 

  resources :genres, only: [:index, :show]

end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
    <ul>
        <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Reading Manager</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>

  <nav>
    <ul>
      <% if logged_in? %>
        <%= link_to "Create a new reading list", new_list_path %> ||
        <%= link_to "My reading lists", reader_lists_path(current_reader) %> || 
        <%= link_to "All reading lists", lists_path %> ||
        <%= link_to "Add a book to the list", new_book_path %> ||
        <%= link_to "All genres", genres_path %> ||
        <%= link_to "All books", books_path %> ||
        <%= link_to "Backt to reader home page", reader_path(current_reader) %> ||
        <%= link_to 'Logout', logout_path %> || 
      <% else %>
        <%= link_to "Sign up", signup_path %> ||
        <%= link_to "Log in", login_path %> 
      <% end %>
      </ul>
    </nav>

    <div>
      <%= @error %>
    </div>

    <%= yield %>

  </body>
</html>